### PR TITLE
enable CodeQL

### PR DESCRIPTION
**Pull request by ljubon**
Working example: https://github.com/ljubon/ParquetSharp/actions/runs/1645731799
NOTE: `autobuild` does not work [link](https://github.com/ljubon/ParquetSharp/actions/runs/1645765371)

### CODE REVIEW

**Review by pavlovic-ivan — COMMENTED** [review]
Should the commented lines be removed?

**Comment by ljubon** [comment]
> Should the commented lines be removed?

@pavlovic-ivan lines are cleaned, my mistake for leaving them in

**Review by pavlovic-ivan — APPROVED** [review]
LGTM. Thx @ljubon

**Comment by ljubon** [comment]
Upstream PR got the change requested https://github.com/G-Research/ParquetSharp/pull/410
Closing this pR

**Pull request closed without merging**
